/**
 * agent_creation.js
 * 
 * Generates a default Minecraft build (a small house) as an array of
 * { x, y, z, type } block objects — the same format used by the
 * litematica viewer's `buildMesh()` pipeline.
 *
 * Called when no .litematic file is loaded so the viewer isn't empty.
 */

export function generateDefaultBuild() {
    const blocks = [];

    function place(x, y, z, type) {
        blocks.push({ x, y, z, type: `minecraft:${type}` });
    }

    // ─── Dimensions ───
    // Outer footprint: 7 wide (x: 0-6) × 7 deep (z: 0-6) × 5 tall walls + roof
    const W = 7, D = 7, WALL_H = 5;

    // ─── Floor (y = 0) ───
    for (let x = 0; x < W; x++)
        for (let z = 0; z < D; z++)
            place(x, 0, z, 'oak_planks');

    // ─── Walls (y = 1 to WALL_H-1) ───
    for (let y = 1; y < WALL_H; y++) {
        for (let x = 0; x < W; x++) {
            for (let z = 0; z < D; z++) {
                const isEdgeX = (x === 0 || x === W - 1);
                const isEdgeZ = (z === 0 || z === D - 1);
                if (!isEdgeX && !isEdgeZ) continue; // interior — skip

                // Door hole: front wall (z = 0), center (x = 3), y = 1-2
                if (z === 0 && x === 3 && y >= 1 && y <= 2) {
                    // Place door blocks
                    if (y === 1) place(x, y, z, 'oak_door[facing=south,half=lower,hinge=left,open=false]');
                    if (y === 2) place(x, y, z, 'oak_door[facing=south,half=upper,hinge=left,open=false]');
                    continue;
                }

                // Windows: side walls, y = 2-3, middle positions
                // Left wall (x = 0): z = 3
                if (x === 0 && (z === 3) && (y === 2 || y === 3)) {
                    place(x, y, z, 'glass_pane[east=true,west=false,north=false,south=false]');
                    continue;
                }
                // Right wall (x = W-1): z = 3
                if (x === W - 1 && (z === 3) && (y === 2 || y === 3)) {
                    place(x, y, z, 'glass_pane[east=false,west=true,north=false,south=false]');
                    continue;
                }
                // Back wall (z = D-1): x = 3
                if (z === D - 1 && (x === 3) && (y === 2 || y === 3)) {
                    place(x, y, z, 'glass_pane[east=false,west=false,north=true,south=false]');
                    continue;
                }

                // Corner posts: use logs
                if (isEdgeX && isEdgeZ) {
                    place(x, y, z, 'oak_log[axis=y]');
                } else {
                    place(x, y, z, 'oak_planks');
                }
            }
        }
    }

    // ─── Ceiling / flat roof base (y = WALL_H) ───
    for (let x = 0; x < W; x++)
        for (let z = 0; z < D; z++)
            place(x, WALL_H, z, 'oak_planks');

    // ─── Pitched Roof (y = WALL_H+1 upward) ───
    // Simple gable roof along x-axis, centered on x
    const roofStart = WALL_H + 1;
    const halfW = Math.floor(W / 2);

    for (let layer = 0; layer <= halfW; layer++) {
        const y = roofStart + layer;
        const xMin = layer;
        const xMax = W - 1 - layer;
        if (xMin > xMax) break;

        for (let x = xMin; x <= xMax; x++) {
            // Overhang: extend 1 block beyond walls
            for (let z = -1; z <= D; z++) {
                if (x === xMin) {
                    place(x, y, z, 'spruce_stairs[facing=east,half=bottom,shape=straight]');
                } else if (x === xMax) {
                    place(x, y, z, 'spruce_stairs[facing=west,half=bottom,shape=straight]');
                } else {
                    place(x, y, z, 'spruce_planks');
                }
            }
        }
    }

    // ─── Interior: Torch on back wall ───
    place(3, 3, D - 2, 'torch');

    // ─── Interior: Crafting table ───
    place(1, 1, D - 2, 'crafting_table');

    // ─── Interior: Chest ───
    place(5, 1, D - 2, 'chest[facing=south]');

    // ─── Interior: Furnace ───
    place(1, 1, 1, 'furnace[facing=south,lit=false]');

    // ─── Small front step ───
    place(3, 0, -1, 'stone_brick_slab[type=bottom]');

    return {
        blocks,
        name: 'AI Architect — Small House',
        description: 'A cozy starter cottage generated by the AI agent'
    };
}
